#!/usr/bin/env python3
"""Generate Lemonade's llama.cpp GGUF architecture allowlist."""

from __future__ import annotations

import argparse
import json
import os
import re
import urllib.parse
import urllib.request
from pathlib import Path

ARCHITECTURE_RE = re.compile(r'\{\s*LLM_ARCH_[A-Z0-9_]+,\s*"([^"]+)"\s*\}')
COMMIT_RE = re.compile(r"Llama\.cpp Commit Hash[^:]*:\s*`?([0-9a-f]+)", re.IGNORECASE)
EXCLUDED_ARCHITECTURES = {"(unknown)", "clip"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--versions",
        default="src/cpp/resources/backend_versions.json",
    )
    parser.add_argument(
        "--output",
        default="src/cpp/include/lemon/llamacpp_architectures_generated.h",
    )
    parser.add_argument(
        "--source",
        action="append",
        metavar="REF=PATH",
        help="Read a pinned llama-arch.cpp from a local file (repeatable)",
    )
    return parser.parse_args()


def architectures_from_sources(sources: dict[str, str]) -> list[str]:
    architecture_sets = [
        set(ARCHITECTURE_RE.findall(source)) for source in sources.values()
    ]
    if not architecture_sets:
        return []
    return sorted(set.intersection(*architecture_sets) - EXCLUDED_ARCHITECTURES)


def fetch_text(url: str) -> str:
    headers = {"User-Agent": "lemonade-architecture-generator"}
    token = os.environ.get("GH_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    with urllib.request.urlopen(
        urllib.request.Request(url, headers=headers)
    ) as response:
        return response.read().decode("utf-8")


def fetch_upstream_source(ref: str) -> str:
    return fetch_text(
        "https://raw.githubusercontent.com/ggml-org/llama.cpp/"
        f"{ref}/src/llama-arch.cpp"
    )


def fetch_rocm_nightly_source(ref: str) -> str:
    release = json.loads(
        fetch_text(
            "https://api.github.com/repos/lemonade-sdk/llamacpp-rocm/"
            f"releases/tags/{ref}"
        )
    )
    commit_match = COMMIT_RE.search(release.get("body") or "")
    if not commit_match:
        raise RuntimeError(f"ROCm release {ref} does not identify its llama.cpp commit")
    short_commit = commit_match.group(1)
    query = urllib.parse.urlencode({"until": release["published_at"], "per_page": 100})
    commits = json.loads(
        fetch_text("https://api.github.com/repos/ggml-org/llama.cpp/commits?" + query)
    )
    matches = [
        commit["sha"] for commit in commits if commit["sha"].startswith(short_commit)
    ]
    if len(matches) != 1:
        raise RuntimeError(
            f"Could not uniquely resolve ROCm release {ref} commit {short_commit}"
        )
    return fetch_upstream_source(matches[0])


def render(configured_refs: list[str], sources: dict[str, str]) -> str:
    architectures = architectures_from_sources(sources)
    if not architectures:
        raise SystemExit("No architectures found in llama-arch.cpp")
    shipped_refs = ", ".join(configured_refs)
    source_refs = ", ".join(sorted(sources))
    entries = "\n".join(f'    "{name}",' for name in architectures)
    return f"""// Generated by .github/scripts/update_llamacpp_architectures.py from
// Common denominator for shipped refs: {shipped_refs}. Sources: {source_refs}.
// Do not edit manually.
#pragma once

#include <algorithm>
#include <array>
#include <string_view>

namespace lemon {{

inline bool llamacpp_architecture_is_supported_by_all_backends(
    std::string_view architecture) {{
    static constexpr std::array<std::string_view, {len(architectures)}> architectures = {{{{
{entries}
    }}}};
    return std::binary_search(architectures.begin(), architectures.end(), architecture);
}}

}}  // namespace lemon
"""


def main() -> int:
    args = parse_args()
    versions = json.loads(Path(args.versions).read_text(encoding="utf-8"))
    pins = versions["llamacpp"]
    configured_refs = sorted(set(pins.values()))
    sources: dict[str, str] = {}
    if args.source:
        for item in args.source:
            try:
                ref, path = item.split("=", 1)
            except ValueError as error:
                raise SystemExit("--source must use REF=PATH") from error
            sources[ref] = Path(path).read_text(encoding="utf-8")
    else:
        rocm_nightly_ref = pins.get("rocm-nightly")
        for ref in configured_refs:
            try:
                sources[ref] = fetch_upstream_source(ref)
            except Exception as error:  # pylint: disable=broad-exception-caught
                if ref == rocm_nightly_ref:
                    try:
                        sources[ref] = fetch_rocm_nightly_source(ref)
                        continue
                    except (
                        Exception
                    ) as rocm_error:  # pylint: disable=broad-exception-caught
                        error = rocm_error
                raise RuntimeError(
                    f"No architecture source found for shipped ref {ref}"
                ) from error
    missing_refs = set(configured_refs) - set(sources)
    unexpected_refs = set(sources) - set(configured_refs)
    if missing_refs or unexpected_refs:
        raise SystemExit(
            f"Architecture sources do not match configured refs: "
            f"missing={sorted(missing_refs)}, unexpected={sorted(unexpected_refs)}"
        )
    Path(args.output).write_text(render(configured_refs, sources), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
